import type { Vehicle } from "./types";

export const defaultVehicle: Vehicle = {
  make: "Tesla",
  model: "Model Y",
  batteryCapacity: 75,
  currentCharge: 65,
  connectorType: "CCS",
  consumption: 6.5, // km per kWh
};

export const vehicles: Vehicle[] = [
  {
    make: "Tesla",
    model: "Model 3",
    batteryCapacity: 75,
    currentCharge: 100,
    connectorType: "CCS",
    consumption: 7.0,
  },
  {
    make: "Tesla",
    model: "Model Y",
    batteryCapacity: 75,
    currentCharge: 100,
    connectorType: "CCS",
    consumption: 6.5,
  },
  {
    make: "Tesla",
    model: "Model S",
    batteryCapacity: 100,
    currentCharge: 100,
    connectorType: "CCS",
    consumption: 6.8,
  },
  {
    make: "Tesla",
    model: "Model X",
    batteryCapacity: 100,
    currentCharge: 100,
    connectorType: "CCS",
    consumption: 6.2,
  },
  {
    make: "Ford",
    model: "Mustang Mach-E",
    batteryCapacity: 98,
    currentCharge: 100,
    connectorType: "CCS",
    consumption: 5.5,
  },
  {
    make: "Chevrolet",
    model: "Bolt EV",
    batteryCapacity: 65,
    currentCharge: 100,
    connectorType: "CCS",
    consumption: 6.0,
  },
  {
    make: "Hyundai",
    model: "Ioniq 5",
    batteryCapacity: 77,
    currentCharge: 100,
    connectorType: "CCS",
    consumption: 6.2,
  },
  {
    make: "Kia",
    model: "EV6",
    batteryCapacity: 77,
    currentCharge: 100,
    connectorType: "CCS",
    consumption: 6.1,
  },
  {
    make: "Volkswagen",
    model: "ID.4",
    batteryCapacity: 82,
    currentCharge: 100,
    connectorType: "CCS",
    consumption: 5.8,
  },
  {
    make: "Audi",
    model: "e-tron",
    batteryCapacity: 95,
    currentCharge: 100,
    connectorType: "CCS",
    consumption: 5.2,
  },
  {
    make: "Jaguar",
    model: "I-PACE",
    batteryCapacity: 90,
    currentCharge: 100,
    connectorType: "CCS",
    consumption: 5.4,
  },
  {
    make: "Porsche",
    model: "Taycan",
    batteryCapacity: 93,
    currentCharge: 100,
    connectorType: "CCS",
    consumption: 5.0,
  },
  {
    make: "Nissan",
    model: "Leaf",
    batteryCapacity: 40,
    currentCharge: 100,
    connectorType: "CHAdeMO",
    consumption: 6.4,
  },
  {
    make: "Renault",
    model: "Zoe",
    batteryCapacity: 52,
    currentCharge: 100,
    connectorType: "Type 2",
    consumption: 7.2,
  },
];
