import type { Vehicle, Station } from './types';

export const userVehicle: Vehicle = {
  make: 'Tesla',
  model: 'Model Y',
  batteryCapacity: 75,
  currentCharge: 65,
};

export const availableStations: Station[] = [
  {
    id: 1,
    name: 'Delhi Connaught Place Charger',
    location: 'Connaught Place, New Delhi',
    distance: 0,
    power: 150,
    pricePerKwh: 18.50,
    connectors: ['CCS', 'Type 2'],
    isAvailable: true,
    lat: 28.6330,
    lng: 77.2193,
  },
  {
    id: 2,
    name: 'Mumbai BKC FastCharge',
    location: 'Bandra Kurla Complex, Mumbai',
    distance: 0,
    power: 50,
    pricePerKwh: 22.00,
    connectors: ['CHAdeMO', 'Type 2'],
    isAvailable: true,
    lat: 19.0689,
    lng: 72.8683,
  },
  {
    id: 3,
    name: 'Bangalore Koramangala Grid',
    location: 'Koramangala, Bengaluru',
    distance: 0,
    power: 250,
    pricePerKwh: 25.00,
    connectors: ['CCS'],
    isAvailable: false,
    lat: 12.9352,
    lng: 77.6245,
  },
  {
    id: 4,
    name: 'Chennai T. Nagar Point',
    location: 'T. Nagar, Chennai',
    distance: 0,
    power: 22,
    pricePerKwh: 15.75,
    connectors: ['Type 2'],
    isAvailable: true,
    lat: 13.0410,
    lng: 80.2339,
  },
  {
    id: 5,
    name: 'Kolkata Park Street Charger',
    location: 'Park Street, Kolkata',
    distance: 0,
    power: 50,
    pricePerKwh: 19.00,
    connectors: ['CCS', 'Type 2'],
    isAvailable: true,
    lat: 22.5526,
    lng: 88.3533,
  },
  {
    id: 6,
    name: 'Hyderabad Hitech City Hub',
    location: 'Hitech City, Hyderabad',
    distance: 0,
    power: 120,
    pricePerKwh: 21.25,
    connectors: ['CCS'],
    isAvailable: true,
    lat: 17.4483,
    lng: 78.3908,
  },
  {
    id: 7,
    name: 'Pune Hinjewadi IT Park',
    location: 'Hinjewadi, Pune',
    distance: 0,
    power: 50,
    pricePerKwh: 20.50,
    connectors: ['Type 2', 'CHAdeMO'],
    isAvailable: false,
    lat: 18.5912,
    lng: 73.7389,
  },
  {
    id: 8,
    name: 'Ahmedabad SG Highway Station',
    location: 'SG Highway, Ahmedabad',
    distance: 0,
    power: 200,
    pricePerKwh: 24.00,
    connectors: ['CCS'],
    isAvailable: true,
    lat: 23.0380,
    lng: 72.5094,
  }
];
